name: clinical_ai_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  google_fonts:
  lucide_icons_flutter:
  http:
  flutter_secure_storage:
  intl:
  provider:
  record:
  path_provider:
  permission_handler:
  web_socket:
  web_socket_channel:
  audioplayers:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - 'assets/'
